# Generated by Django 3.1.5 on 2021-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_Tensak', '0006_usersguiderequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersguiderequests',
            name='user_number',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
