# Generated by Django 3.1.5 on 2021-04-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_Tensak', '0007_auto_20210420_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersguiderequests',
            old_name='message',
            new_name='user_message',
        ),
    ]
